apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
    paths:
    - path: /simple
      backend:
        serviceName: simple-container-service
        servicePort: 31110
    - path: /
      backend:
        serviceName: simple-container-service
        servicePort: 31110