apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-ingress
spec:
  defaultBackend:
    service:
      name: simple-container-service
      port:
        number: 31110
  rules:
  - host: 
    http:
      paths:
      - path: /simple
        pathType: Prefix
        backend:
          service:
            name: simple-container-service
            port:
              number: 31110
      - path: /app
        pathType: Prefix
        backend:
          service:
            name: simple-container-service
            port:
              number: 31110