apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
    paths:
    - path: /simple
      backend:
        serviceName: simple-container-service
        servicePort: 5000
    - path: /app
      backend:
        serviceName: simple-container-service
        servicePort: 5000